language: python
python:
  - "3.4"
  - "3.5"

install:
  - "pip install -r e_shopping/requirement.txt"
  - "pip install codecov"

script: python e_shopping/manage.py test --settings=e_shopping.settings.travistest myshopping users

notifications:
  email: false

after_success:
  - codecov

install : True
