# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='event',
        ),
    ]
