# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 14:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(blank=True, null=True)),
                ('product_price_limit', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='myshopping.Product')),
            ],
            options={
                'verbose_name_plural': 'ShoppingCart',
                'verbose_name': 'ShoppingCart',
            },
        ),
    ]
