# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
