# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0004_order_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Incomplete', 'INCOMPLETE'), ('Pending', 'PENDING'), ('Processed', 'PROCESSED'), ('Returned', 'RETURNED'), ('Canceled', 'CANCELED')], default='', max_length=50, verbose_name='User Order Status'),
            preserve_default=False,
        ),
    ]
