# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0005_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Processed', 'PROCESSED'), ('Returned', 'RETURNED'), ('Canceled', 'CANCELED')], max_length=50, verbose_name='User Order Status'),
        ),
    ]
