# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventgiftcondition'),
        ('myshopping', '0009_auto_20160208_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_event', to='event.Event'),
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_event', to='event.Event'),
        ),
    ]
