# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Comment'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 2, 6)),
            preserve_default=False,
        ),
    ]
