# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160206_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Title'),
        ),
    ]
