# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
