# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_event'),
        ('event', '0004_auto_20160210_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to='users.UserProfile'),
        ),
    ]
