# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_event'),
        ('event', '0005_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGiftCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Event')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_userevent', to='users.UserProfile')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_userevent', to='users.UserProfile')),
            ],
            options={
                'verbose_name': 'EventGift',
                'verbose_name_plural': 'EventGifts',
            },
        ),
    ]
