# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventgiftcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgiftcondition',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
