# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventgiftcondition_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgiftcondition',
            name='product_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
